### ISSUE TITLE
Inconsistency between layer levels and zoom levels

### ISSUE THREAD

**Issue by R4to0** [blind-coder/pz-to-deepzoom#1]
First of all, thank you for your splendid work on this project!

From what I can say these scripts works without any kind of error message. The only issue is that it seems there are probably some calculation issue somewhere that makes zoom level tiles shift to black or to another random tile file when you zoom it a bit. Additionally the 1+ layer levels are also off from layer 0.

Compiled mapmap from [ibrbus-improvedvegetation](https://github.com/blind-coder/pz-mapmap/tree/ibrbus-improvedvegetation) branch but I first tried WP with the one in release section and had the same issue.

I've uploaded examples here:
https://map.r4to0.wtf/?desc=Otr_20210916_L0
https://map.r4to0.wtf/?desc=OtrSr_20210916_L0
Only Over the River (and the bridge that connects the map on the right side) is available from there but I also had the same issue with West Point Expansion so I believe there's some miscalculation somewhere.

PS: I've ripped off the page files from your site so sorry if that wasn't allowed, let me know and I'll take my link down if needed.

**Comment by blind-coder** [comment]
Hmm, I remember having that issue in the past. It stems from a mis-calculation during the deepzoom calculation.
Can you do me a favor: Delete the output and run the deepzoom with a single thread:
```
rm -rf work* map.xml map_files
make THREADS=1
```

**Comment by R4to0** [comment]
> 
> 
> Hmm, I remember having that issue in the past. It stems from a mis-calculation during the deepzoom calculation. Can you do me a favor: Delete the output and run the deepzoom with a single thread:
> 
> ```
> rm -rf work* map.xml map_files
> make THREADS=1
> ```

Sadly it did have no effect. Judging from the shell scripts, you already left everything set as threads=1 and no parameters to set those were passed. Setting THREADS=1 or not the result was the same.

https://map.r4to0.wtf/?desc=Otr_20210916_L0
https://map.r4to0.wtf/?desc=OtrSr_20210916_L0

Level 0 is jpg (as it don't need transparency) but others are png, not sure if that makes any difference and I see that on your official site is that way for the vanilla map (I believe it is because of its HUGE size heh, can't even imagine the patience you had to generate all of that).

Long short story, in level 0 specific tiles are loaded as black or shifted, level 1+ are off from 0 and have the same shifting issue as L0.

![image](https://user-images.githubusercontent.com/3608184/141420366-a3b2057f-e71a-4969-a8f2-afd6151dc069.png)

![image](https://user-images.githubusercontent.com/3608184/141419907-724517f0-d2dd-4503-a026-e142817500c0.png)
https://map.r4to0.wtf/?desc=Otr_20210916_L0#0.41855168468337584,0.2835145768724458,12.097735766298566

You can count with me for more testing when needed :)

**Comment by blind-coder** [comment]
Damn, would have been too  easy of a fix, I guess. I'll pull the OTR map and give it a try myself. It worked well with the Challenge map.
Just to note, the main map takes about 3-4 weeks on my computer, although I only run the scripts for 8-10 hours a day.

**Comment by blind-coder** [comment]
Okay, I found the issue. Maps that don't resolve to multiples of 1024 in both dimensions for all layers that require multiple images in the respective dimension run into this problem. I'm testing a possible fix right now.

**Comment by blind-coder** [comment]
I have pushed a possible fix into https://github.com/blind-coder/pz-to-deepzoom/tree/issue_1
You'll need to do the same again as above:
```
rm -rf work* map.xml map_files
make THREADS=1
```
Could you try this?

**Comment by R4to0** [comment]
> 
> 
> I have pushed a possible fix into https://github.com/blind-coder/pz-to-deepzoom/tree/issue_1 You'll need to do the same again as above:
> 
> ```
> rm -rf work* map.xml map_files
> make THREADS=1
> ```
> 
> Could you try this?

That did, layer 0 is good now! Now only the position between level 0 and level 1+ are what is remaining.

![image](https://user-images.githubusercontent.com/3608184/141600374-0ae080cd-e3bf-442e-a6d2-7f2cc19e4666.png)
![image](https://user-images.githubusercontent.com/3608184/141600470-85b67250-7f11-47aa-8266-b51c3dac2f26.png)

Edit: layer = level

**Comment by blind-coder** [comment]
O-kay, let me think. There was a nasty little thing. You need to do this:
After you finish layer 0, you need to keep the bottom-right-most output-* image and copy it before the upper layers. I need to find a good way to integrate that into the upper layers.
Basically, after doing layer 0, check in the tmp/ directory for the output-XXX-YYY.png file with the highest XXX and YYY values respectively. Copy that file to a safe place.
Then for layers 1 and above, run:
```
make tmp/stitch.ok
rm -f tmp/stitch.ok
cp output-XXX-YYY.png tmp/
make tmp/stitch.ok
make
```

That should fix the upper layers. Now, I need to find a way to integrate this into a Makefile flow...

**Comment by blind-coder** [comment]
Alternatively, it might work if you just copy the map.xml file from Level 0 to Level 1, 2, etc, but I'm not sure about that.

**Comment by R4to0** [comment]
Sorry for the delay. Didn't managed to get working the way you mentioned about keeping the highest xy coord file, I may got confused at some point. As for copying the map.xml file I did tried on the ones I generated and didn't worked, unless that has to be done when generating levels (ie.: without deleting map.xml before building next level tiles).

For integrating with makefile I wish I could help on that but haven't understood that way you did, had nightmares when working with makefiles in the past so I stick with bash scripts only, I believe you did the makefile way for processing in steps few hours a day instead of doing everything from beginning everytime make is ran, right?

**Comment by blind-coder** [comment]
No problem, was just a hunch anyway.
I have an idea on how this could be done in the Makefile, I'll look into it. I'm travelling for the rest of the week on business so I may not get around to it until the weekend, though.

Yes, the Makefile approach was partly for resuming easily, but also for parallelizing and dependency tracking. `make -j 2` is much easier than trying to properly handle that in a bash script.

**Comment by blind-coder** [comment]
I just pushed a small change into issue_1 branch that should address this. You'll need to re-run `make LAYER=0` to remember the largest tile and it'll be used automatically when you run the higher layers. It happens in https://github.com/blind-coder/pz-to-deepzoom/blob/issue_1/remembermax.sh which saves the tile if run on LAYER=0 and restores it on LAYER=1.

For easier use I have added `make clean` which will clean the temporary files for the LAYER only, keeping MapMap output and the temp file from remembermax.sh in place.

**Comment by R4to0** [comment]
> No problem, was just a hunch anyway. I have an idea on how this could be done in the Makefile, I'll look into it. I'm travelling for the rest of the week on business so I may not get around to it until the weekend, though.

No rush. Take your time and stay safe during the travel!

> Yes, the Makefile approach was partly for resuming easily, but also for parallelizing and dependency tracking. `make -j 2` is much easier than trying to properly handle that in a bash script.

Sadly it takes an impressive amount of ram to parallelize! I also had race conditions between zoom level tile generation when I tried with 2 and 3 threads, eg.: when generating the last file for map_files/17/ the makefile started resizing for /16/ and got an operation not permitted error as both threads were using the same file. No issues with single threaded processing.

And you're right, doing with Makefile is easier with its builtin functionality than with batch scripts where you have to do all the logic yourself.

> 
> 
> I just pushed a small change into issue_1 branch that should address this. You'll need to re-run `make LAYER=0` to remember the largest tile and it'll be used automatically when you run the higher layers. It happens in https://github.com/blind-coder/pz-to-deepzoom/blob/issue_1/remembermax.sh which saves the tile if run on LAYER=0 and restores it on LAYER=1.
> 
> For easier use I have added `make clean` which will clean the temporary files for the LAYER only, keeping MapMap output and the temp file from remembermax.sh in place.

Thank you a lot for the hard work! Will try as soon as I can and let you know about the results.

**Comment by blind-coder** [comment]
I push one more commit to issue_1 just now that you'll probably need. It runs filltransparent again after restoring the file in remembermax.sh. Otherwise you'll lack a lot of intermittent files.

**Comment by R4to0** [comment]
Started all the conversion from scratch with the latest commits from that branch. Seems to be pretty close now, level 1 tiles are very little off from 0 this time (off by 1 I think).

[Over the river secondary route](https://steamcommunity.com/workshop/filedetails/?id=2603239477) (small and faster to test)
![image](https://user-images.githubusercontent.com/3608184/142377089-128e3b91-d5b4-42db-aacc-05fe956979ef.png)

![image](https://user-images.githubusercontent.com/3608184/142377204-c0a8fcbb-5149-43c8-8ed6-efc6f15bf1eb.png)

**Comment by blind-coder** [comment]
I don't see a levelchooser item on https://map.r4to0.wtf/?desc=OtrSr_20210916_L0, you'll need to define one so the Y level is set correctly.

**Comment by R4to0** [comment]
Apologies for that, I forgot to push the updated index.html file for that one, should be there once the CDN edge cache expires.
If not I'll check out the hosting later once I wake up.
Sorry for bringing all this trouble to you 😅

6am job before sleep💤

**Comment by blind-coder** [comment]
Cache has cleared and I see it now. The map scripts are correct, the map itself is wrong. The roof sits one tile too low on the Y axis. You can verify this by checking the dino oil sign, it is correct:
![image](https://user-images.githubusercontent.com/3063912/142418546-062376f7-e59a-404b-8885-22f64c0c3615.png)

I'm afraid you'll have to fix the map :-)

**Comment by R4to0** [comment]
> 
> 
> Cache has cleared and I see it now. The map scripts are correct, the map itself is wrong. The roof sits one tile too low on the Y axis. You can verify this by checking the dino oil sign, it is correct: ![image](https://user-images.githubusercontent.com/3063912/142418546-062376f7-e59a-404b-8885-22f64c0c3615.png)
> 
> I'm afraid you'll have to fix the map :-)

Oof, my bad then. Should've used another map to test 😅

I'm generating Over the River again for another comparison.

**Comment by R4to0** [comment]
Pushed all the tiles for OTR https://map.r4to0.wtf/?desc=Otr_20210916_L0

Weirdly all the lamps are fine (L0+L1):
![image](https://user-images.githubusercontent.com/3608184/142561513-d0fd991f-273a-4c95-a962-d9948ecc77b4.png)

But if you check the house tiles L1+ they're all off by one from L0.
![image](https://user-images.githubusercontent.com/3608184/142561843-15a4dff3-64f0-4a72-bd56-24e8f69ba8b6.png)
![image](https://user-images.githubusercontent.com/3608184/142561877-c02f2fc0-4be0-42ac-a699-0c7995c9e13c.png)

Did I made any mistake while generating them? This is how I am doing:
```
*Edit makefile to make layer 0 as JPG*
make LAYER=0
*move map_files dir and map.xml to the website maps dir related to its layer*
*Edit makefile to make layer 1+ as PNG*
make clean && make LAYER=1
*move map_files dir and map.xml to the website maps dir related to its layer*
make clean && make LAYER=2
*move map_files dir and map.xml to the website maps dir related to its layer*
...
till LAYER=7
```

**Comment by blind-coder** [comment]
The commands are fine, I'll be travelling back home today, then I can open the map in WorldZed and double check.

**Comment by R4to0** [comment]
[Same issue with West Point Expansion](https://steamcommunity.com/sharedfiles/filedetails/?id=2195155059)
![image](https://user-images.githubusercontent.com/3608184/142588121-0c142bb3-c49c-48fc-88f3-6d29979f71ef.png)
![image](https://user-images.githubusercontent.com/3608184/142588217-ff052085-61a4-48cd-8784-c16503c271f1.png)

> 
> 
> I'll be travelling back home today

Take your time and be safe during the travel, that's your top priority now :)

**Comment by R4to0** [comment]
Seems like this isn't related to the shell/makefile scripts in this repository, but the way the site shows them. Comparing individual pngs side by side with your site and what I generated they actually matches positions 100%, its just the website shifting them somehow. I guess this is case closed for the original issue.

**Comment by R4to0** [comment]
NAILED IT!

![image](https://user-images.githubusercontent.com/3608184/142780150-307dc928-62a6-4ea6-9622-92e9e9522572.png)
![image](https://user-images.githubusercontent.com/3608184/142780156-820432eb-afc3-4088-952c-8c64103b7a67.png)
![image](https://user-images.githubusercontent.com/3608184/142780187-cb97000c-6ed4-469c-97c7-e4b1d74adc57.png)

The extra.json was needed for the map to set the multiply value to 2, which fixes this issue! YAY

**Comment by blind-coder** [comment]
Hah, I actually thought of the same thing during the last two days and wanted to comment that same thing this morning :)
So happy that it works correctly now! I'll merge this branch into main later then :-)

**Comment by R4to0** [comment]
Generating other tiles here. When viewing only some are like **one pixel** off when you zoom in, could be something related to canvas rendering but I wouldn't bother about that now. Other than that LGTM to go to main branch, unless you want to generate the extra.json file as well.

After all that I wouldn't mind sending you all the generated tiles I have for a few community maps in case you want to put in the official website as everyone would benefit from that (and god, Raven Creek takes almost 30GB with L0 being jpg and others png!).

Thanks for all the hard work!

**Comment by blind-coder** [comment]
That's either canvas rendering or resize artifacts. As for the extra.json file, that's not part of this solution, that should go to the map website. There's a large heap of work to be done there as well.
